### ISSUE TITLE
Create Enum for Bot Events

### ISSUE THREAD

**Issue by uvulpos** [Goscord/goscord#12]
Hi there,

In your discord bot, I found this example: 

```go
  _ = client.On("ready", event.OnReady(client, cmdManager))
  _ = client.On("interactionCreate", cmdManager.Handler(client))
  _ = client.On("guildMemberAdd", event.OnGuildMemberAdd(client))
```

and as a professional software developer I want to have a list of possible server events suggested by my ide, so I would suggest to create a custom type of string, so the code could look like this:

```go
  import "github.com/Goscord/goscord/goscord/events"
  _ = client.On(events.EventReady, event.OnReady(client, cmdManager))
  _ = client.On(events.EventInteractionCreate, cmdManager.Handler(client))
  _ = client.On(events.EventGuildMemberAdd, event.OnGuildMemberAdd(client))
```

see in the node js documentation: https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files

**Comment by szerookii** [comment]
ima push something in [dev branch](https://github.com/Goscord/goscord/tree/dev).

**Comment by uvulpos** [comment]
For documentation reason, I would appreciate it if you could also paste the future answer to this issue so people from Google can find it as well :)

**Comment by szerookii** [comment]
Refactored [event system](https://github.com/Goscord/goscord/blob/dev/test/test.go#L22)

**Comment by Bluzzi** [comment]
> For documentation reason, I would appreciate it if you could also paste the future answer to this issue so people from Google can find it as well :)

On the next version of our website, we are preparing more relevant documentation and examples. 

This should arrive at the same time as the V1 of Goscord.
