### ISSUE TITLE
cannot find module providing package due to -mod=readonly

### ISSUE THREAD

**Issue by biohazardxxx** [Goscord/goscord#20]
Hi, still a noob on GoLang so not sure if this should rather go to StackOverflow but hope this isssue is placed correct here.

After installing the package, I copied over the example from the https://goscord.dev/ main page I get error:
error while importing github.com/Goscord/goscord/goscord: cannot find module providing package github.com/Goscord/goscord/goscord/discord/embed: import lookup disabled by -mod=readonly

Same error for the other imports 
	"github.com/Goscord/goscord/goscord/discord"
	"github.com/Goscord/goscord/goscord/gateway"
	"github.com/Goscord/goscord/goscord/gateway/event"
I am using Visual Studio Code.

Anyone has hints please?

**Comment by biohazardxxx** [comment]
It will be on my end as I could run https://github.com/Goscord/bot fine I will open an SO question.

**Comment by biohazardxxx** [comment]
StackOverflow  issue was closed as the package is broken:
"Do you know of a version of that module which works? The latest commit of the module you are trying to import is broken. There are no packages called github.com/Goscord/goscord or github.com/Goscord/goscord/discord, and github.com/Goscord/goscord/goscord doesn't work because it imports other packages that don't exist. If the module ever worked, you will need to specify the exact version to use."

So I am reopening this one!

**Comment by szerookii** [comment]
Hello, take a look at #21. Sorry for response time.
