### ISSUE TITLE
Discord Server issue

### ISSUE THREAD

**Issue by dimkauzh** [Goscord/goscord#24]
Hi, so i tried joining the goscord discord server, but when I joined I didn't see any channels (see screenshot). Could someone help? Or maybe report to the moderators?
![Screenshot_2024-03-24-13-03-11-334_com discord-edit](https://github.com/Goscord/goscord/assets/106883655/463ca52e-7471-4fc1-b8fa-a02d122b4be3)

**Comment by jonhorner** [comment]
@djpiper28 Same for me - I just get a messages failed to load error when trying to join

**Comment by djpiper28** [comment]
> @djpiper28 Same for me - I just get a messages failed to load error when trying to join
> 

I don't run the discord server.

**Comment by szerookii** [comment]
Discord server has been discontinued for now.
